export const LANGUAGES = [
  { code: "de", name: "Deutsch",    flag: "🇩🇪", tagline: "Wähle deine Sprache für das Legal Onboarding" },
  { code: "ro", name: "Română",     flag: "🇷🇴", tagline: "Alege limba pentru onboardingul legal" },
  { code: "en", name: "English",    flag: "🇬🇧", tagline: "Choose your language for Legal Onboarding" },
  { code: "fr", name: "Français",   flag: "🇫🇷", tagline: "Choisissez votre langue pour l'onboarding légal" },
  { code: "es", name: "Español",    flag: "🇪🇸", tagline: "Elige tu idioma para el onboarding legal" },
  { code: "it", name: "Italiano",   flag: "🇮🇹", tagline: "Scegli la tua lingua per l'onboarding legale" },
  { code: "ru", name: "Русский",    flag: "🇷🇺", tagline: "Выберите язык для правового онбординга" },
  { code: "pl", name: "Polski",     flag: "🇵🇱", tagline: "Wybierz język dla onboardingu prawnego" },
  { code: "cs", name: "Čeština",    flag: "🇨🇿", tagline: "Vyberte jazyk pro právní onboarding" },
  { code: "hu", name: "Magyar",     flag: "🇭🇺", tagline: "Válasszon nyelvet a jogi onboardinghoz" },
];

export const TRANSLATIONS = {
  de: {
    // StepCard navigation
    btnNext: "Weiter", btnBack: "Zurück", btnSaveExit: "Speichern & beenden",
    // StepWelcome
    welcomeTitleGuided: "Willkommen zum geführten Onboarding", welcomeTitle: "Willkommen bei gingr",
    welcomeDescGuided: "Du begleitest jetzt eine Escort durch das legale Onboarding. Folge den Schritten gemeinsam.",
    welcomeDesc: "Wir führen dich Schritt für Schritt durch alles, was du brauchst, um legal in der Schweiz zu arbeiten.",
    welcomeStat1Title: "~15 Minuten", welcomeStat1Desc: "Durchschnittliche Dauer",
    welcomeStat2Title: "100% sicher", welcomeStat2Desc: "Verschlüsselte Daten",
    welcomeStat3Title: "Jederzeit pausieren", welcomeStat3Desc: "Autosave aktiv",
    welcomeChecklist: "Was du bereit haben solltest:",
    welcomeItem1: "Identitätskarte oder Pass",
    welcomeItem2: "Aufenthaltsbewilligung (falls nicht Schweizer*in)",
    welcomeItem3: "AHV Bestätigung oder Handelsregisterauszug (falls du Selbstständig tätig bist)",
    welcomeItem4: "Deine Bankverbindung / IBAN",
    welcomeStart: "Jetzt starten →",
    // ModeSelector
    title: "Legal Onboarding", subtitle: "Wie möchtest du das Onboarding starten?",
    selfTitle: "Ich mache es selbst YO", selfDesc: "Du wirst Schritt für Schritt durch den Prozess geführt — in deinem eigenen Tempo.", selfBtn: "Starten →",
    guidedTitle: "Mit gingr-Mitarbeiter", guidedDesc: "Ein Teammitglied von gingr begleitet dich persönlich durch das Onboarding.", guidedBtn: "Termin buchen →",
    admin: "Admin-Dashboard", modalTitle: "Termin buchen", modalSubtitle: "Onboarding mit gingr-Begleitung",
    modalIntro: "Bitte halte folgende Dokumente bereit, bevor du deinen Termin buchst:",
    doc1Title: "Ausweis / Pass", doc1Desc: "Reisepass oder Personalausweis (gültig)",
    doc2Title: "Aufenthaltsbewilligung", doc2Desc: "Für Nicht-Schweizer: Permit B, C, L oder ähnliches",
    doc3Title: "Selbständige: Gewerbenachweis", doc3Desc: "UID-Nummer und Handelsregisterauszug oder ähnliches",
    bookBtn: "Jetzt Termin buchen →", langLabel: "Sprache wählen",
    homeOnboardingTitle: "Onboarding starten", homeOnboardingDesc: "Schritt für Schritt durch dein rechtliches Setup — sicher und einfach.", homeOnboardingBtn: "Jetzt starten",
    homeDocsTitle: "Meine Dokumente", homeDocsDesc: "Verträge, Status und hochgeladene Dokumente einsehen.", homeDocsBtn: "Einloggen",
    homeNeedHelp: "Brauchst du Hilfe?",
    // StepWorkModel
    workModelTitle: "Wähle dein Arbeitsmodell", workModelSubtitle: "Das bestimmt, welche Verträge und Dokumente du benötigst.",
    workModel1Label: "Angestellte (unbefristet)", workModel1Desc: "Du arbeitest als Angestellte bei gingr. Unbefristeter Vertrag.",
    workModel1Pro1: "Lohnabrechnung & Sozialversicherung durch gingr", workModel1Pro2: "Klare rechtliche Absicherung", workModel1Pro3: "Für CH / EU / Permit C",
    workModel2Label: "Angestellte (max. 90 Tage)", workModel2Desc: "Kurzfristiges Anstellungsverhältnis, bis 90 Tage pro Jahr.",
    workModel2Pro1: "Für Permit B/L geeignet", workModel2Pro2: "Flexibel & unkompliziert", workModel2Pro3: "Quellensteuer inklusive",
    workModel3Label: "Selbständig", workModel3Desc: "Du arbeitest auf eigene Rechnung als selbständige Escort.",
    workModel3Pro1: "Eigenes Unternehmen / UID-Nummer erforderlich", workModel3Pro2: "Mehr Flexibilität", workModel3Pro3: "Eigene Buchhaltung",
    // StepCoreData
    coreDataTitle: "Deine persönlichen Daten", coreDataSubtitle: "Diese Angaben werden für deinen Vertrag und die Lohnabrechnung verwendet.",
    labelFirstName: "Vorname", labelLastName: "Nachname", labelDob: "Geburtsdatum",
    labelEmail: "E-Mail-Adresse", labelPhone: "Telefonnummer", labelNationality: "Nationalität",
    labelCitizenshipGroup: "Staatsbürgerschaft", citizenshipCH: "🇨🇭 Schweiz", citizenshipEU: "🇪🇺 EU / EFTA", citizenshipNonEU: "🌍 Drittstaaten",
    labelAddress: "Strasse und Hausnummer", labelCity: "Ort", labelPostalCode: "PLZ",
    errorAge: "Du musst mindestens 18 Jahre alt sein.",
    errorEmailExists: "Diese E-Mail ist bereits registriert.", errorPhoneExists: "Diese Telefonnummer ist bereits registriert.",
    magicLinkSent: "Wir haben dir einen Link geschickt, um dein bestehendes Profil fortzusetzen.",
    existingAccountHint: "Du hast bereits ein Konto? Klicke hier um fortzufahren.",
    selectNationality: "Land auswählen…", searchNationality: "Suchen…",
    idUploadLabelSwiss: "Schweizer Pass oder Identitätskarte hochladen *",
    idUploadLabelForeign: "Reisepass oder Personalausweis hochladen *",
    sendingLink: "Wird gesendet…", sendEmailLink: "Login-Link per E-Mail senden", sendSmsLink: "Login-Link per SMS senden",
    // StepResidency
    residencyTitle: "Aufenthaltsbewilligung", residencySubtitle: "Da du keine Schweizer Bürgerin bist, benötigen wir deinen Aufenthaltsausweis.",
    permitLabel: "Art des Ausweises",
    permitB: "Ausweis B", permitBDesc: "Aufenthaltsbewilligung",
    permitC: "Ausweis C", permitCDesc: "Niederlassungsbewilligung",
    permitL: "Ausweis L", permitLDesc: "Kurzaufenthaltsbewilligung",
    permitOther: "Anderer", permitOtherDesc: "Anderer Aufenthaltstitel",
    uploadPermitLabel: "Ausweis hochladen",
    uploadPermitHint: "Vorder- und Rückseite sichtbar, Text lesbar, nicht abgelaufen",
    residencyPendingNote: "⏳ Nach dem Upload wird dein Ausweis von unserem Team geprüft. Du kannst in der Zwischenzeit mit dem Onboarding fortfahren.",
    errorNoPermitType: "Bitte wähle deinen Aufenthaltsausweis aus.",
    errorNoPermitDoc: "Bitte lade deinen Ausweis hoch, um fortzufahren.",
  },
  en: {
    // StepCard navigation
    btnNext: "Next", btnBack: "Back", btnSaveExit: "Save & exit",
    // StepWelcome
    welcomeTitleGuided: "Welcome to the guided onboarding", welcomeTitle: "Welcome to gingr",
    welcomeDescGuided: "You are now guiding an escort through the legal onboarding. Follow the steps together.",
    welcomeDesc: "We guide you step by step through everything you need to work legally in Switzerland.",
    welcomeStat1Title: "~15 minutes", welcomeStat1Desc: "Average duration",
    welcomeStat2Title: "100% secure", welcomeStat2Desc: "Encrypted data",
    welcomeStat3Title: "Pause anytime", welcomeStat3Desc: "Autosave enabled",
    welcomeChecklist: "What you should have ready:",
    welcomeItem1: "ID card or passport",
    welcomeItem2: "Residence permit (if not Swiss)",
    welcomeItem3: "AHV confirmation or commercial register extract (if self-employed)",
    welcomeItem4: "Your bank details / IBAN",
    welcomeStart: "Start now →",
    // ModeSelector
    title: "Legal Onboarding", subtitle: "How would you like to start the onboarding?",
    selfTitle: "I'll do it myself", selfDesc: "You'll be guided step by step through the process — at your own pace.", selfBtn: "Get started →",
    guidedTitle: "With a gingr team member", guidedDesc: "A gingr team member will personally guide you through the onboarding.", guidedBtn: "Book appointment →",
    admin: "Admin Dashboard", modalTitle: "Book appointment", modalSubtitle: "Onboarding with gingr guidance",
    modalIntro: "Please have the following documents ready before booking your appointment:",
    doc1Title: "ID / Passport", doc1Desc: "Valid passport or national ID",
    doc2Title: "Residence permit", doc2Desc: "For non-Swiss: Permit B, C, L or similar",
    doc3Title: "Self-employed: Business proof", doc3Desc: "UID number and commercial register extract or similar",
    bookBtn: "Book appointment now →", langLabel: "Choose language",
    homeOnboardingTitle: "Start Legal Onboarding", homeOnboardingDesc: "Complete your compliance steps to unlock secure booking and your legal setup.", homeOnboardingBtn: "Start Onboarding",
    homeDocsTitle: "Access My Documents", homeDocsDesc: "Log in to view your contracts, status, and uploaded documents.", homeDocsBtn: "Log In",
    homeNeedHelp: "Need help?",
    // StepWorkModel
    workModelTitle: "Choose your work model", workModelSubtitle: "This determines which contracts and documents you need.",
    workModel1Label: "Employee (permanent)", workModel1Desc: "You work as an employee at gingr. Permanent contract.",
    workModel1Pro1: "Payroll & social insurance handled by gingr", workModel1Pro2: "Clear legal protection", workModel1Pro3: "For CH / EU / Permit C",
    workModel2Label: "Employee (max. 90 days)", workModel2Desc: "Short-term employment, up to 90 days per year.",
    workModel2Pro1: "Suitable for Permit B/L", workModel2Pro2: "Flexible & simple", workModel2Pro3: "Withholding tax included",
    workModel3Label: "Self-employed", workModel3Desc: "You work independently as a self-employed escort.",
    workModel3Pro1: "Own company / UID number required", workModel3Pro2: "More flexibility", workModel3Pro3: "Own accounting",
    // StepCoreData
    coreDataTitle: "Your personal data", coreDataSubtitle: "This information is used for your contract and payroll.",
    labelFirstName: "First name", labelLastName: "Last name", labelDob: "Date of birth",
    labelEmail: "Email address", labelPhone: "Phone number", labelNationality: "Nationality",
    labelCitizenshipGroup: "Citizenship", citizenshipCH: "🇨🇭 Switzerland", citizenshipEU: "🇪🇺 EU / EFTA", citizenshipNonEU: "🌍 Non-EU",
    labelAddress: "Street and house number", labelCity: "City", labelPostalCode: "Postal code",
    errorAge: "You must be at least 18 years old.",
    errorEmailExists: "This email is already registered.", errorPhoneExists: "This phone number is already registered.",
    magicLinkSent: "We sent you a link to continue your existing profile.",
    existingAccountHint: "Already have an account? Click here to continue.",
    selectNationality: "Select country…", searchNationality: "Search…",
    idUploadLabelSwiss: "Upload Swiss passport or ID card *",
    idUploadLabelForeign: "Upload passport or national ID *",
    sendingLink: "Sending…", sendEmailLink: "Send login link via email", sendSmsLink: "Send login link via SMS",
    // StepResidency
    residencyTitle: "Residence permit", residencySubtitle: "Since you are not a Swiss citizen, we need your residence permit.",
    permitLabel: "Permit type",
    permitB: "Permit B", permitBDesc: "Residence permit",
    permitC: "Permit C", permitCDesc: "Settlement permit",
    permitL: "Permit L", permitLDesc: "Short-term permit",
    permitOther: "Other", permitOtherDesc: "Other residence title",
    uploadPermitLabel: "Upload permit",
    uploadPermitHint: "Front and back visible, text legible, not expired",
    residencyPendingNote: "⏳ After upload, your permit will be reviewed by our team. You can continue with the onboarding in the meantime.",
    errorNoPermitType: "Please select your residence permit type.",
    errorNoPermitDoc: "Please upload your permit to continue.",
  },
  fr: {
    // StepCard navigation
    btnNext: "Suivant", btnBack: "Retour", btnSaveExit: "Enregistrer et quitter",
    // StepWelcome
    welcomeTitleGuided: "Bienvenue dans l'onboarding guidé", welcomeTitle: "Bienvenue sur gingr",
    welcomeDescGuided: "Vous accompagnez maintenant une escorte dans l'onboarding légal. Suivez les étapes ensemble.",
    welcomeDesc: "Nous vous guidons étape par étape à travers tout ce dont vous avez besoin pour travailler légalement en Suisse.",
    welcomeStat1Title: "~15 minutes", welcomeStat1Desc: "Durée moyenne",
    welcomeStat2Title: "100% sécurisé", welcomeStat2Desc: "Données chiffrées",
    welcomeStat3Title: "Pause à tout moment", welcomeStat3Desc: "Sauvegarde automatique",
    welcomeChecklist: "Ce que vous devriez avoir sous la main :",
    welcomeItem1: "Carte d'identité ou passeport",
    welcomeItem2: "Permis de séjour (si vous n'êtes pas Suisse)",
    welcomeItem3: "Confirmation AVS ou extrait du registre du commerce (si indépendant)",
    welcomeItem4: "Vos coordonnées bancaires / IBAN",
    welcomeStart: "Commencer maintenant →",
    // ModeSelector
    title: "Onboarding Légal", subtitle: "Comment souhaitez-vous démarrer l'onboarding ?",
    selfTitle: "Je le fais moi-même", selfDesc: "Vous serez guidé pas à pas à travers le processus — à votre propre rythme.", selfBtn: "Commencer →",
    guidedTitle: "Avec un employé gingr", guidedDesc: "Un membre de l'équipe gingr vous accompagnera personnellement dans l'onboarding.", guidedBtn: "Prendre rendez-vous →",
    admin: "Tableau de bord Admin", modalTitle: "Prendre rendez-vous", modalSubtitle: "Onboarding avec accompagnement gingr",
    modalIntro: "Veuillez préparer les documents suivants avant de prendre rendez-vous :",
    doc1Title: "Carte d'identité / Passeport", doc1Desc: "Passeport ou carte d'identité valide",
    doc2Title: "Permis de séjour", doc2Desc: "Pour les non-Suisses : Permis B, C, L ou similaire",
    doc3Title: "Indépendants : Preuve d'activité", doc3Desc: "Numéro IDE et extrait du registre du commerce ou similaire",
    bookBtn: "Prendre rendez-vous maintenant →", langLabel: "Choisir la langue",
    homeOnboardingTitle: "Commencer l'onboarding", homeOnboardingDesc: "Complétez votre configuration légale étape par étape.", homeOnboardingBtn: "Démarrer",
    homeDocsTitle: "Mes documents", homeDocsDesc: "Consultez vos contrats, statuts et documents téléversés.", homeDocsBtn: "Se connecter",
    homeNeedHelp: "Besoin d'aide ?",
    // StepWorkModel
    workModelTitle: "Choisissez votre modèle de travail", workModelSubtitle: "Cela détermine quels contrats et documents sont nécessaires.",
    workModel1Label: "Employée (permanent)", workModel1Desc: "Vous travaillez comme employée chez gingr. Contrat permanent.",
    workModel1Pro1: "Salaire & assurances sociales gérés par gingr", workModel1Pro2: "Protection juridique claire", workModel1Pro3: "Pour CH / UE / Permis C",
    workModel2Label: "Employée (max. 90 jours)", workModel2Desc: "Relation de travail à court terme, jusqu'à 90 jours par an.",
    workModel2Pro1: "Adapté au permis B/L", workModel2Pro2: "Flexible & simple", workModel2Pro3: "Impôt à la source inclus",
    workModel3Label: "Indépendante", workModel3Desc: "Vous travaillez à votre compte comme escort indépendante.",
    workModel3Pro1: "Entreprise propre / numéro UID requis", workModel3Pro2: "Plus de flexibilité", workModel3Pro3: "Comptabilité propre",
  },
  es: {
    // StepCard navigation
    btnNext: "Siguiente", btnBack: "Atrás", btnSaveExit: "Guardar y salir",
    // StepWelcome
    welcomeTitleGuided: "Bienvenido al onboarding guiado", welcomeTitle: "Bienvenido a gingr",
    welcomeDescGuided: "Ahora estás acompañando a una escort en el onboarding legal. Sigue los pasos juntos.",
    welcomeDesc: "Te guiamos paso a paso por todo lo que necesitas para trabajar legalmente en Suiza.",
    welcomeStat1Title: "~15 minutos", welcomeStat1Desc: "Duración media",
    welcomeStat2Title: "100% seguro", welcomeStat2Desc: "Datos cifrados",
    welcomeStat3Title: "Pausar en cualquier momento", welcomeStat3Desc: "Guardado automático activo",
    welcomeChecklist: "Lo que deberías tener listo:",
    welcomeItem1: "Documento de identidad o pasaporte",
    welcomeItem2: "Permiso de residencia (si no eres suizo/a)",
    welcomeItem3: "Confirmación AHV o extracto del registro mercantil (si eres autónomo/a)",
    welcomeItem4: "Tus datos bancarios / IBAN",
    welcomeStart: "Empezar ahora →",
    // ModeSelector
    title: "Incorporación Legal", subtitle: "¿Cómo deseas iniciar el proceso de incorporación?",
    selfTitle: "Lo hago yo mismo", selfDesc: "Serás guiado paso a paso por el proceso — a tu propio ritmo.", selfBtn: "Empezar →",
    guidedTitle: "Con un empleado de gingr", guidedDesc: "Un miembro del equipo de gingr te acompañará personalmente en el proceso.", guidedBtn: "Reservar cita →",
    admin: "Panel de Administración", modalTitle: "Reservar cita", modalSubtitle: "Incorporación con acompañamiento de gingr",
    modalIntro: "Por favor, tenga listos los siguientes documentos antes de reservar su cita:",
    doc1Title: "DNI / Pasaporte", doc1Desc: "Pasaporte o DNI válido",
    doc2Title: "Permiso de residencia", doc2Desc: "Para no suizos: Permiso B, C, L o similar",
    doc3Title: "Autónomos: Prueba de actividad", doc3Desc: "Número UID y extracto del registro mercantil o similar",
    bookBtn: "Reservar cita ahora →", langLabel: "Elegir idioma",
    homeOnboardingTitle: "Iniciar incorporación", homeOnboardingDesc: "Completa tu configuración legal paso a paso.", homeOnboardingBtn: "Empezar",
    homeDocsTitle: "Mis documentos", homeDocsDesc: "Accede a tus contratos, estado y documentos subidos.", homeDocsBtn: "Iniciar sesión",
    homeNeedHelp: "¿Necesitas ayuda?",
    // StepWorkModel
    workModelTitle: "Elige tu modelo de trabajo", workModelSubtitle: "Esto determina qué contratos y documentos necesitas.",
    workModel1Label: "Empleado (permanente)", workModel1Desc: "Trabajas como empleada en gingr. Contrato permanente.",
    workModel1Pro1: "Nómina y seguridad social gestionadas por gingr", workModel1Pro2: "Protección legal clara", workModel1Pro3: "Para CH / UE / Permiso C",
    workModel2Label: "Empleado (máx. 90 días)", workModel2Desc: "Relación laboral a corto plazo, hasta 90 días por año.",
    workModel2Pro1: "Apto para permiso B/L", workModel2Pro2: "Flexible y sencillo", workModel2Pro3: "Impuesto en la fuente incluido",
    workModel3Label: "Autónomo", workModel3Desc: "Trabajas por tu cuenta como escort independiente.",
    workModel3Pro1: "Empresa propia / número UID requerido", workModel3Pro2: "Más flexibilidad", workModel3Pro3: "Contabilidad propia",
  },
  it: {
    // StepCard navigation
    btnNext: "Avanti", btnBack: "Indietro", btnSaveExit: "Salva ed esci",
    // StepWelcome
    welcomeTitleGuided: "Benvenuto nell'onboarding guidato", welcomeTitle: "Benvenuto su gingr",
    welcomeDescGuided: "Stai ora accompagnando un'escort nell'onboarding legale. Segui i passaggi insieme.",
    welcomeDesc: "Ti guidiamo passo dopo passo attraverso tutto ciò di cui hai bisogno per lavorare legalmente in Svizzera.",
    welcomeStat1Title: "~15 minuti", welcomeStat1Desc: "Durata media",
    welcomeStat2Title: "100% sicuro", welcomeStat2Desc: "Dati crittografati",
    welcomeStat3Title: "Pausa in qualsiasi momento", welcomeStat3Desc: "Salvataggio automatico attivo",
    welcomeChecklist: "Cosa dovresti avere a portata di mano:",
    welcomeItem1: "Carta d'identità o passaporto",
    welcomeItem2: "Permesso di soggiorno (se non sei svizzero/a)",
    welcomeItem3: "Conferma AVS o estratto del registro di commercio (se sei lavoratore autonomo)",
    welcomeItem4: "Le tue coordinate bancarie / IBAN",
    welcomeStart: "Inizia ora →",
    // ModeSelector
    title: "Onboarding Legale", subtitle: "Come desideri iniziare l'onboarding?",
    selfTitle: "Lo faccio da solo", selfDesc: "Sarai guidato passo dopo passo nel processo — ai tuoi ritmi.", selfBtn: "Inizia →",
    guidedTitle: "Con un membro del team gingr", guidedDesc: "Un membro del team gingr ti accompagnerà personalmente nell'onboarding.", guidedBtn: "Prenota appuntamento →",
    admin: "Dashboard Admin", modalTitle: "Prenota appuntamento", modalSubtitle: "Onboarding con accompagnamento gingr",
    modalIntro: "Si prega di avere i seguenti documenti pronti prima di prenotare:",
    doc1Title: "Documento d'identità / Passaporto", doc1Desc: "Passaporto o carta d'identità valida",
    doc2Title: "Permesso di soggiorno", doc2Desc: "Per i non svizzeri: Permesso B, C, L o simile",
    doc3Title: "Autonomi: Prova di attività", doc3Desc: "Numero UID ed estratto del registro commerciale o simile",
    bookBtn: "Prenota ora →", langLabel: "Scegli lingua",
    homeOnboardingTitle: "Inizia l'onboarding", homeOnboardingDesc: "Completa la tua configurazione legale passo dopo passo.", homeOnboardingBtn: "Inizia",
    homeDocsTitle: "I miei documenti", homeDocsDesc: "Accedi ai tuoi contratti, stato e documenti caricati.", homeDocsBtn: "Accedi",
    homeNeedHelp: "Hai bisogno di aiuto?",
    // StepWorkModel
    workModelTitle: "Scegli il tuo modello di lavoro", workModelSubtitle: "Questo determina quali contratti e documenti sono necessari.",
    workModel1Label: "Dipendente (tempo indeterminato)", workModel1Desc: "Lavori come dipendente presso gingr. Contratto a tempo indeterminato.",
    workModel1Pro1: "Busta paga e assicurazioni sociali gestite da gingr", workModel1Pro2: "Chiara tutela legale", workModel1Pro3: "Per CH / UE / Permesso C",
    workModel2Label: "Dipendente (max 90 giorni)", workModel2Desc: "Rapporto di lavoro a breve termine, fino a 90 giorni all'anno.",
    workModel2Pro1: "Adatto per permesso B/L", workModel2Pro2: "Flessibile e semplice", workModel2Pro3: "Imposta alla fonte inclusa",
    workModel3Label: "Autonomo", workModel3Desc: "Lavori per conto tuo come escort indipendente.",
    workModel3Pro1: "Azienda propria / numero UID richiesto", workModel3Pro2: "Maggiore flessibilità", workModel3Pro3: "Contabilità propria",
  },
  ro: {
    // StepCard navigation
    btnNext: "Următorul", btnBack: "Înapoi", btnSaveExit: "Salvează și ieși",
    // StepWelcome
    welcomeTitleGuided: "Bun venit la onboardingul ghidat", welcomeTitle: "Bun venit pe gingr",
    welcomeDescGuided: "Acum însoțești o escortă prin onboardingul legal. Urmați pașii împreună.",
    welcomeDesc: "Vă ghidăm pas cu pas prin tot ce aveți nevoie pentru a lucra legal în Elveția.",
    welcomeStat1Title: "~15 minute", welcomeStat1Desc: "Durată medie",
    welcomeStat2Title: "100% sigur", welcomeStat2Desc: "Date criptate",
    welcomeStat3Title: "Pauză oricând", welcomeStat3Desc: "Salvare automată activă",
    welcomeChecklist: "Ce ar trebui să ai pregătit:",
    welcomeItem1: "Carte de identitate sau pașaport",
    welcomeItem2: "Permis de ședere (dacă nu ești elvețian/ă)",
    welcomeItem3: "Confirmare AVS sau extras din registrul comerțului (dacă ești independent/ă)",
    welcomeItem4: "Datele tale bancare / IBAN",
    welcomeStart: "Începe acum →",
    // ModeSelector
    title: "Onboarding Legal", subtitle: "Cum dorești să începi procesul de onboarding?",
    selfTitle: "Fac singur", selfDesc: "Vei fi ghidat pas cu pas prin proces — în propriul tău ritm.", selfBtn: "Începe →",
    guidedTitle: "Cu un angajat gingr", guidedDesc: "Un membru al echipei gingr te va însoți personal prin onboarding.", guidedBtn: "Programează întâlnire →",
    admin: "Panou Admin", modalTitle: "Programează întâlnire", modalSubtitle: "Onboarding cu însoțitor gingr",
    modalIntro: "Te rugăm să ai la îndemână următoarele documente înainte de programare:",
    doc1Title: "Act de identitate / Pașaport", doc1Desc: "Pașaport sau carte de identitate valabilă",
    doc2Title: "Permis de ședere", doc2Desc: "Pentru non-elvețieni: Permis B, C, L sau similar",
    doc3Title: "PFA: Dovadă de activitate", doc3Desc: "Număr UID și extras din registrul comerțului sau similar",
    bookBtn: "Programează acum →", langLabel: "Alege limba",
    homeOnboardingTitle: "Începe onboardingul", homeOnboardingDesc: "Completează-ți configurarea legală pas cu pas.", homeOnboardingBtn: "Începe",
    homeDocsTitle: "Documentele mele", homeDocsDesc: "Accesează contractele, statusul și documentele încărcate.", homeDocsBtn: "Autentificare",
    homeNeedHelp: "Ai nevoie de ajutor?",
    // StepWorkModel
    workModelTitle: "Alege modelul tău de lucru", workModelSubtitle: "Acest lucru determină ce contracte și documente sunt necesare.",
    workModel1Label: "Angajată (permanent)", workModel1Desc: "Lucrezi ca angajată la gingr. Contract permanent.",
    workModel1Pro1: "Salariu și asigurări sociale gestionate de gingr", workModel1Pro2: "Protecție legală clară", workModel1Pro3: "Pentru CH / UE / Permis C",
    workModel2Label: "Angajată (max. 90 zile)", workModel2Desc: "Angajare pe termen scurt, până la 90 de zile pe an.",
    workModel2Pro1: "Potrivit pentru permis B/L", workModel2Pro2: "Flexibil și simplu", workModel2Pro3: "Impozit la sursă inclus",
    workModel3Label: "Independent", workModel3Desc: "Lucrezi pe cont propriu ca escortă independentă.",
    workModel3Pro1: "Companie proprie / număr UID necesar", workModel3Pro2: "Mai multă flexibilitate", workModel3Pro3: "Contabilitate proprie",
  },
  ru: {
    // StepCard navigation
    btnNext: "Далее", btnBack: "Назад", btnSaveExit: "Сохранить и выйти",
    // StepWelcome
    welcomeTitleGuided: "Добро пожаловать в сопровождаемый онбординг", welcomeTitle: "Добро пожаловать на gingr",
    welcomeDescGuided: "Вы сейчас сопровождаете эскорта через правовой онбординг. Следуйте шагам вместе.",
    welcomeDesc: "Мы проведём вас шаг за шагом через всё, что необходимо для легальной работы в Швейцарии.",
    welcomeStat1Title: "~15 минут", welcomeStat1Desc: "Средняя продолжительность",
    welcomeStat2Title: "100% безопасно", welcomeStat2Desc: "Зашифрованные данные",
    welcomeStat3Title: "Пауза в любое время", welcomeStat3Desc: "Автосохранение активно",
    welcomeChecklist: "Что вам следует подготовить:",
    welcomeItem1: "Удостоверение личности или паспорт",
    welcomeItem2: "Вид на жительство (если вы не гражданин/ка Швейцарии)",
    welcomeItem3: "Подтверждение AHV или выписка из торгового реестра (если вы самозанятый/ая)",
    welcomeItem4: "Ваши банковские реквизиты / IBAN",
    welcomeStart: "Начать сейчас →",
    // ModeSelector
    title: "Правовой онбординг", subtitle: "Как вы хотите начать процесс онбординга?",
    selfTitle: "Я сделаю это сам", selfDesc: "Вы будете проходить процесс шаг за шагом — в своём собственном темпе.", selfBtn: "Начать →",
    guidedTitle: "С сотрудником gingr", guidedDesc: "Член команды gingr лично сопроводит вас через онбординг.", guidedBtn: "Записаться →",
    admin: "Панель администратора", modalTitle: "Записаться на встречу", modalSubtitle: "Онбординг с сопровождением gingr",
    modalIntro: "Пожалуйста, подготовьте следующие документы перед записью:",
    doc1Title: "Удостоверение личности / Паспорт", doc1Desc: "Действующий паспорт или удостоверение личности",
    doc2Title: "Вид на жительство", doc2Desc: "Для неграждан Швейцарии: разрешение B, C, L или аналогичное",
    doc3Title: "Самозанятые: Подтверждение деятельности", doc3Desc: "Номер UID и выписка из торгового реестра или аналогичное",
    bookBtn: "Записаться сейчас →", langLabel: "Выбрать язык",
    homeOnboardingTitle: "Начать онбординг", homeOnboardingDesc: "Пройдите юридическую настройку шаг за шагом.", homeOnboardingBtn: "Начать",
    homeDocsTitle: "Мои документы", homeDocsDesc: "Просматривайте контракты, статус и загруженные документы.", homeDocsBtn: "Войти",
    homeNeedHelp: "Нужна помощь?",
    // StepWorkModel
    workModelTitle: "Выберите модель работы", workModelSubtitle: "Это определяет, какие договоры и документы вам нужны.",
    workModel1Label: "Сотрудник (постоянный)", workModel1Desc: "Вы работаете как сотрудник в gingr. Бессрочный контракт.",
    workModel1Pro1: "Зарплата и соцстрахование через gingr", workModel1Pro2: "Чёткая юридическая защита", workModel1Pro3: "Для CH / ЕС / Permit C",
    workModel2Label: "Сотрудник (макс. 90 дней)", workModel2Desc: "Краткосрочная занятость до 90 дней в год.",
    workModel2Pro1: "Подходит для Permit B/L", workModel2Pro2: "Гибко и просто", workModel2Pro3: "Налог у источника включён",
    workModel3Label: "Самозанятая", workModel3Desc: "Вы работаете как независимая эскорт.",
    workModel3Pro1: "Собственная компания / номер UID обязателен", workModel3Pro2: "Больше гибкости", workModel3Pro3: "Собственная бухгалтерия",
  },
  pl: {
    // StepCard navigation
    btnNext: "Dalej", btnBack: "Wstecz", btnSaveExit: "Zapisz i zakończ",
    // StepWelcome
    welcomeTitleGuided: "Witamy w onboardingu z przewodnikiem", welcomeTitle: "Witamy w gingr",
    welcomeDescGuided: "Teraz przeprowadzasz eskortę przez onboarding prawny. Postępujcie razem zgodnie z krokami.",
    welcomeDesc: "Przeprowadzimy Cię krok po kroku przez wszystko, czego potrzebujesz, aby legalnie pracować w Szwajcarii.",
    welcomeStat1Title: "~15 minut", welcomeStat1Desc: "Średni czas trwania",
    welcomeStat2Title: "100% bezpieczne", welcomeStat2Desc: "Zaszyfrowane dane",
    welcomeStat3Title: "Pauza w dowolnym momencie", welcomeStat3Desc: "Automatyczny zapis aktywny",
    welcomeChecklist: "Co powinieneś/powinnaś mieć pod ręką:",
    welcomeItem1: "Dowód osobisty lub paszport",
    welcomeItem2: "Zezwolenie na pobyt (jeśli nie jesteś Szwajcarem/Szwajcarką)",
    welcomeItem3: "Potwierdzenie AHV lub wypis z rejestru handlowego (jeśli jesteś samozatrudniony/a)",
    welcomeItem4: "Twoje dane bankowe / IBAN",
    welcomeStart: "Zacznij teraz →",
    // ModeSelector
    title: "Onboarding Prawny", subtitle: "Jak chcesz rozpocząć proces onboardingu?",
    selfTitle: "Zrobię to sam", selfDesc: "Będziesz prowadzony krok po kroku przez cały proces — we własnym tempie.", selfBtn: "Zacznij →",
    guidedTitle: "Z pracownikiem gingr", guidedDesc: "Członek zespołu gingr osobiście przeprowadzi Cię przez onboarding.", guidedBtn: "Zarezerwuj spotkanie →",
    admin: "Panel Administracyjny", modalTitle: "Zarezerwuj spotkanie", modalSubtitle: "Onboarding z asystą gingr",
    modalIntro: "Przygotuj następujące dokumenty przed rezerwacją spotkania:",
    doc1Title: "Dowód tożsamości / Paszport", doc1Desc: "Ważny paszport lub dowód osobisty",
    doc2Title: "Zezwolenie na pobyt", doc2Desc: "Dla osób spoza Szwajcarii: Zezwolenie B, C, L lub podobne",
    doc3Title: "Samozatrudnieni: Dowód działalności", doc3Desc: "Numer UID i wyciąg z rejestru handlowego lub podobne",
    bookBtn: "Zarezerwuj teraz →", langLabel: "Wybierz język",
    homeOnboardingTitle: "Rozpocznij onboarding", homeOnboardingDesc: "Ukończ konfigurację prawną krok po kroku.", homeOnboardingBtn: "Zacznij",
    homeDocsTitle: "Moje dokumenty", homeDocsDesc: "Przeglądaj swoje umowy, status i przesłane dokumenty.", homeDocsBtn: "Zaloguj się",
    homeNeedHelp: "Potrzebujesz pomocy?",
    // StepWorkModel
    workModelTitle: "Wybierz model pracy", workModelSubtitle: "To określa, jakie umowy i dokumenty są potrzebne.",
    workModel1Label: "Pracownik (stały)", workModel1Desc: "Pracujesz jako pracownik w gingr. Umowa na czas nieokreślony.",
    workModel1Pro1: "Lista płac i ubezpieczenie przez gingr", workModel1Pro2: "Jasna ochrona prawna", workModel1Pro3: "Dla CH / UE / Permit C",
    workModel2Label: "Pracownik (maks. 90 dni)", workModel2Desc: "Krótkoterminowe zatrudnienie do 90 dni rocznie.",
    workModel2Pro1: "Odpowiednie dla Permit B/L", workModel2Pro2: "Elastyczne i proste", workModel2Pro3: "Podatek u źródła wliczony",
    workModel3Label: "Samozatrudniona", workModel3Desc: "Pracujesz na własny rachunek jako escort.",
    workModel3Pro1: "Własna firma / numer UID wymagany", workModel3Pro2: "Większa elastyczność", workModel3Pro3: "Własna księgowość",
  },
  cs: {
    // StepCard navigation
    btnNext: "Další", btnBack: "Zpět", btnSaveExit: "Uložit a ukončit",
    // StepWelcome
    welcomeTitleGuided: "Vítejte v řízeném onboardingu", welcomeTitle: "Vítejte na gingr",
    welcomeDescGuided: "Nyní provázíte escort právním onboardingem. Postupujte společně podle kroků.",
    welcomeDesc: "Provedeme vás krok za krokem vším, co potřebujete k legální práci ve Švýcarsku.",
    welcomeStat1Title: "~15 minut", welcomeStat1Desc: "Průměrná doba trvání",
    welcomeStat2Title: "100% bezpečné", welcomeStat2Desc: "Zašifrovaná data",
    welcomeStat3Title: "Kdykoliv pozastavit", welcomeStat3Desc: "Automatické ukládání aktivní",
    welcomeChecklist: "Co byste měli mít připraveno:",
    welcomeItem1: "Občanský průkaz nebo pas",
    welcomeItem2: "Povolení k pobytu (pokud nejste Švýcar/ka)",
    welcomeItem3: "Potvrzení AHV nebo výpis z obchodního rejstříku (pokud jste OSVČ)",
    welcomeItem4: "Vaše bankovní údaje / IBAN",
    welcomeStart: "Začít nyní →",
    // ModeSelector
    title: "Právní onboarding", subtitle: "Jak chcete zahájit proces onboardingu?",
    selfTitle: "Udělám to sám", selfDesc: "Budete provázeni krok za krokem procesem — vlastním tempem.", selfBtn: "Začít →",
    guidedTitle: "S pracovníkem gingr", guidedDesc: "Člen týmu gingr vás osobně provede onboardingem.", guidedBtn: "Rezervovat schůzku →",
    admin: "Administrátorský panel", modalTitle: "Rezervovat schůzku", modalSubtitle: "Onboarding s asistencí gingr",
    modalIntro: "Před rezervací schůzky si prosím připravte následující dokumenty:",
    doc1Title: "Občanský průkaz / Pas", doc1Desc: "Platný cestovní pas nebo občanský průkaz",
    doc2Title: "Povolení k pobytu", doc2Desc: "Pro neobčany Švýcarska: Povolení B, C, L nebo podobné",
    doc3Title: "OSVČ: Doklad o činnosti", doc3Desc: "Číslo UID a výpis z obchodního rejstříku nebo podobné",
    bookBtn: "Rezervovat nyní →", langLabel: "Vybrat jazyk",
    homeOnboardingTitle: "Zahájit onboarding", homeOnboardingDesc: "Dokončete svůj právní setup krok za krokem.", homeOnboardingBtn: "Začít",
    homeDocsTitle: "Moje dokumenty", homeDocsDesc: "Zobrazit smlouvy, stav a nahrané dokumenty.", homeDocsBtn: "Přihlásit se",
    homeNeedHelp: "Potřebujete pomoc?",
    // StepWorkModel
    workModelTitle: "Vyberte pracovní model", workModelSubtitle: "To určuje, jaké smlouvy a dokumenty potřebujete.",
    workModel1Label: "Zaměstnanec (na dobu neurčitou)", workModel1Desc: "Pracujete jako zaměstnanec u gingr. Smlouva na dobu neurčitou.",
    workModel1Pro1: "Mzda a sociální pojištění přes gingr", workModel1Pro2: "Jasná právní ochrana", workModel1Pro3: "Pro CH / EU / Permit C",
    workModel2Label: "Zaměstnanec (max. 90 dní)", workModel2Desc: "Krátkodobé zaměstnání až 90 dní ročně.",
    workModel2Pro1: "Vhodné pro Permit B/L", workModel2Pro2: "Flexibilní a jednoduché", workModel2Pro3: "Srážková daň zahrnuta",
    workModel3Label: "OSVČ", workModel3Desc: "Pracujete na vlastní účet jako samostatná escort.",
    workModel3Pro1: "Vlastní firma / UID číslo nutné", workModel3Pro2: "Více flexibility", workModel3Pro3: "Vlastní účetnictví",
  },
  hu: {
    // StepCard navigation
    btnNext: "Tovább", btnBack: "Vissza", btnSaveExit: "Mentés és kilépés",
    // StepWelcome
    welcomeTitleGuided: "Üdvözöljük a végigvezetett onboardingban", welcomeTitle: "Üdvözöljük a gingr-en",
    welcomeDescGuided: "Most egy eskort végigvezet a jogi onboardingon. Kövesse együtt a lépéseket.",
    welcomeDesc: "Lépésről lépésre végigvezetjük mindenen, amire szüksége van a Svájcban való legális munkavégzéshez.",
    welcomeStat1Title: "~15 perc", welcomeStat1Desc: "Átlagos időtartam",
    welcomeStat2Title: "100% biztonságos", welcomeStat2Desc: "Titkosított adatok",
    welcomeStat3Title: "Bármikor szüneteltethető", welcomeStat3Desc: "Automatikus mentés aktív",
    welcomeChecklist: "Amire szüksége lesz:",
    welcomeItem1: "Személyi igazolvány vagy útlevél",
    welcomeItem2: "Tartózkodási engedély (ha nem svájci állampolgár)",
    welcomeItem3: "AHV-igazolás vagy cégjegyzékkivonat (ha önfoglalkoztató)",
    welcomeItem4: "Bankadatai / IBAN",
    welcomeStart: "Kezdés most →",
    // ModeSelector
    title: "Jogi Onboarding", subtitle: "Hogyan szeretné megkezdeni az onboarding folyamatot?",
    selfTitle: "Magam csinálom", selfDesc: "Lépésről lépésre vezet végig a folyamaton — a saját tempójában.", selfBtn: "Kezdés →",
    guidedTitle: "Egy gingr munkatárssal", guidedDesc: "A gingr csapat egyik tagja személyesen kíséri végig az onboardingon.", guidedBtn: "Időpont foglalása →",
    admin: "Admin irányítópult", modalTitle: "Időpont foglalása", modalSubtitle: "Onboarding gingr kísérettel",
    modalIntro: "Kérjük, készítse elő a következő dokumentumokat az időpont foglalása előtt:",
    doc1Title: "Személyi igazolvány / Útlevél", doc1Desc: "Érvényes útlevél vagy személyi igazolvány",
    doc2Title: "Tartózkodási engedély", doc2Desc: "Nem svájci állampolgároknak: B, C, L engedély vagy hasonló",
    doc3Title: "Önfoglalkoztatók: Tevékenységigazolás", doc3Desc: "UID szám és cégkivonát vagy hasonló",
    bookBtn: "Foglaljon most →", langLabel: "Nyelv kiválasztása",
    homeOnboardingTitle: "Onboarding indítása", homeOnboardingDesc: "Töltse ki a jogi beállítást lépésről lépésre.", homeOnboardingBtn: "Kezdés",
    homeDocsTitle: "Dokumentumaim", homeDocsDesc: "Tekintse meg szerződéseit, státuszát és feltöltött dokumentumait.", homeDocsBtn: "Bejelentkezés",
    homeNeedHelp: "Segítségre van szüksége?",
    // StepWorkModel
    workModelTitle: "Válaszd ki a munkamodellt", workModelSubtitle: "Ez határozza meg, milyen szerződésekre és dokumentumokra van szükség.",
    workModel1Label: "Alkalmazott (határozatlan)", workModel1Desc: "A gingr alkalmazottjaként dolgozol. Határozatlan idejű szerződés.",
    workModel1Pro1: "Bérszámfejtés és társadalombiztosítás a gingr által", workModel1Pro2: "Egyértelmű jogi védelem", workModel1Pro3: "CH / EU / C engedélyhez",
    workModel2Label: "Alkalmazott (max. 90 nap)", workModel2Desc: "Rövid távú foglalkoztatás, évente legfeljebb 90 nap.",
    workModel2Pro1: "B/L engedélyhez megfelelő", workModel2Pro2: "Rugalmas és egyszerű", workModel2Pro3: "Forrásadóval együtt",
    workModel3Label: "Önálló vállalkozó", workModel3Desc: "Saját számlára dolgozol mint független escort.",
    workModel3Pro1: "Saját cég / UID szám szükséges", workModel3Pro2: "Több rugalmasság", workModel3Pro3: "Saját könyvelés",
  },
};

export function getStoredLanguage() {
  try {
    const code = localStorage.getItem("gingr_lang") || "de";
    return LANGUAGES.find((l) => l.code === code) || LANGUAGES[0];
  } catch {
    return LANGUAGES[0];
  }
}

export function storeLanguage(lang) {
  try {
    localStorage.setItem("gingr_lang", lang.code);
  } catch {}
}