export const LANGUAGES = [
  { code: "de", name: "Deutsch",    flag: "🇩🇪", tagline: "Wähle deine Sprache für das Legal Onboarding" },
  { code: "ro", name: "Română",     flag: "🇷🇴", tagline: "Alege limba pentru onboardingul legal" },
  { code: "en", name: "English",    flag: "🇬🇧", tagline: "Choose your language for Legal Onboarding" },
  { code: "fr", name: "Français",   flag: "🇫🇷", tagline: "Choisissez votre langue pour l'onboarding légal" },
  { code: "es", name: "Español",    flag: "🇪🇸", tagline: "Elige tu idioma para el onboarding legal" },
  { code: "it", name: "Italiano",   flag: "🇮🇹", tagline: "Scegli la tua lingua per l'onboarding legale" },
  { code: "ru", name: "Русский",    flag: "🇷🇺", tagline: "Выберите язык для правового онбординга" },
  { code: "pl", name: "Polski",     flag: "🇵🇱", tagline: "Wybierz język dla onboardingu prawnego" },
  { code: "cs", name: "Čeština",    flag: "🇨🇿", tagline: "Vyberte jazyk pro právní onboarding" },
  { code: "hu", name: "Magyar",     flag: "🇭🇺", tagline: "Válasszon nyelvet a jogi onboardinghoz" },
];

export const TRANSLATIONS = {
  de: {
    title: "Legal Onboarding", subtitle: "Wie möchtest du das Onboarding starten?",
    selfTitle: "Ich mache es selbst", selfDesc: "Du wirst Schritt für Schritt durch den Prozess geführt — in deinem eigenen Tempo.", selfBtn: "Starten →",
    guidedTitle: "Mit gingr-Mitarbeiter", guidedDesc: "Ein Teammitglied von gingr begleitet dich persönlich durch das Onboarding.", guidedBtn: "Termin buchen →",
    admin: "Admin-Dashboard", modalTitle: "Termin buchen", modalSubtitle: "Onboarding mit gingr-Begleitung",
    modalIntro: "Bitte halte folgende Dokumente bereit, bevor du deinen Termin buchst:",
    doc1Title: "Ausweis / Pass", doc1Desc: "Reisepass oder Personalausweis (gültig)",
    doc2Title: "Aufenthaltsbewilligung", doc2Desc: "Für Nicht-Schweizer: Permit B, C, L oder ähnliches",
    doc3Title: "Selbständige: Gewerbenachweis", doc3Desc: "UID-Nummer und Handelsregisterauszug oder ähnliches",
    bookBtn: "Jetzt Termin buchen →", langLabel: "Sprache wählen",
    homeOnboardingTitle: "Onboarding starten", homeOnboardingDesc: "Schritt für Schritt durch dein rechtliches Setup — sicher und einfach.", homeOnboardingBtn: "Jetzt starten",
    homeDocsTitle: "Meine Dokumente", homeDocsDesc: "Verträge, Status und hochgeladene Dokumente einsehen.", homeDocsBtn: "Einloggen",
    homeNeedHelp: "Brauchst du Hilfe?",
  },
  en: {
    title: "Legal Onboarding", subtitle: "How would you like to start the onboarding?",
    selfTitle: "I'll do it myself", selfDesc: "You'll be guided step by step through the process — at your own pace.", selfBtn: "Get started →",
    guidedTitle: "With a gingr team member", guidedDesc: "A gingr team member will personally guide you through the onboarding.", guidedBtn: "Book appointment →",
    admin: "Admin Dashboard", modalTitle: "Book appointment", modalSubtitle: "Onboarding with gingr guidance",
    modalIntro: "Please have the following documents ready before booking your appointment:",
    doc1Title: "ID / Passport", doc1Desc: "Valid passport or national ID",
    doc2Title: "Residence permit", doc2Desc: "For non-Swiss: Permit B, C, L or similar",
    doc3Title: "Self-employed: Business proof", doc3Desc: "UID number and commercial register extract or similar",
    bookBtn: "Book appointment now →", langLabel: "Choose language",
    homeOnboardingTitle: "Start Legal Onboarding", homeOnboardingDesc: "Complete your compliance steps to unlock secure booking and your legal setup.", homeOnboardingBtn: "Start Onboarding",
    homeDocsTitle: "Access My Documents", homeDocsDesc: "Log in to view your contracts, status, and uploaded documents.", homeDocsBtn: "Log In",
    homeNeedHelp: "Need help?",
  },
  fr: {
    title: "Onboarding Légal", subtitle: "Comment souhaitez-vous démarrer l'onboarding ?",
    selfTitle: "Je le fais moi-même", selfDesc: "Vous serez guidé pas à pas à travers le processus — à votre propre rythme.", selfBtn: "Commencer →",
    guidedTitle: "Avec un employé gingr", guidedDesc: "Un membre de l'équipe gingr vous accompagnera personnellement dans l'onboarding.", guidedBtn: "Prendre rendez-vous →",
    admin: "Tableau de bord Admin", modalTitle: "Prendre rendez-vous", modalSubtitle: "Onboarding avec accompagnement gingr",
    modalIntro: "Veuillez préparer les documents suivants avant de prendre rendez-vous :",
    doc1Title: "Carte d'identité / Passeport", doc1Desc: "Passeport ou carte d'identité valide",
    doc2Title: "Permis de séjour", doc2Desc: "Pour les non-Suisses : Permis B, C, L ou similaire",
    doc3Title: "Indépendants : Preuve d'activité", doc3Desc: "Numéro IDE et extrait du registre du commerce ou similaire",
    bookBtn: "Prendre rendez-vous maintenant →", langLabel: "Choisir la langue",
    homeOnboardingTitle: "Commencer l'onboarding", homeOnboardingDesc: "Complétez votre configuration légale étape par étape.", homeOnboardingBtn: "Démarrer",
    homeDocsTitle: "Mes documents", homeDocsDesc: "Consultez vos contrats, statuts et documents téléversés.", homeDocsBtn: "Se connecter",
    homeNeedHelp: "Besoin d'aide ?",
  },
  es: {
    title: "Incorporación Legal", subtitle: "¿Cómo deseas iniciar el proceso de incorporación?",
    selfTitle: "Lo hago yo mismo", selfDesc: "Serás guiado paso a paso por el proceso — a tu propio ritmo.", selfBtn: "Empezar →",
    guidedTitle: "Con un empleado de gingr", guidedDesc: "Un miembro del equipo de gingr te acompañará personalmente en el proceso.", guidedBtn: "Reservar cita →",
    admin: "Panel de Administración", modalTitle: "Reservar cita", modalSubtitle: "Incorporación con acompañamiento de gingr",
    modalIntro: "Por favor, tenga listos los siguientes documentos antes de reservar su cita:",
    doc1Title: "DNI / Pasaporte", doc1Desc: "Pasaporte o DNI válido",
    doc2Title: "Permiso de residencia", doc2Desc: "Para no suizos: Permiso B, C, L o similar",
    doc3Title: "Autónomos: Prueba de actividad", doc3Desc: "Número UID y extracto del registro mercantil o similar",
    bookBtn: "Reservar cita ahora →", langLabel: "Elegir idioma",
    homeOnboardingTitle: "Iniciar incorporación", homeOnboardingDesc: "Completa tu configuración legal paso a paso.", homeOnboardingBtn: "Empezar",
    homeDocsTitle: "Mis documentos", homeDocsDesc: "Accede a tus contratos, estado y documentos subidos.", homeDocsBtn: "Iniciar sesión",
    homeNeedHelp: "¿Necesitas ayuda?",
  },
  it: {
    title: "Onboarding Legale", subtitle: "Come desideri iniziare l'onboarding?",
    selfTitle: "Lo faccio da solo", selfDesc: "Sarai guidato passo dopo passo nel processo — ai tuoi ritmi.", selfBtn: "Inizia →",
    guidedTitle: "Con un membro del team gingr", guidedDesc: "Un membro del team gingr ti accompagnerà personalmente nell'onboarding.", guidedBtn: "Prenota appuntamento →",
    admin: "Dashboard Admin", modalTitle: "Prenota appuntamento", modalSubtitle: "Onboarding con accompagnamento gingr",
    modalIntro: "Si prega di avere i seguenti documenti pronti prima di prenotare:",
    doc1Title: "Documento d'identità / Passaporto", doc1Desc: "Passaporto o carta d'identità valida",
    doc2Title: "Permesso di soggiorno", doc2Desc: "Per i non svizzeri: Permesso B, C, L o simile",
    doc3Title: "Autonomi: Prova di attività", doc3Desc: "Numero UID ed estratto del registro commerciale o simile",
    bookBtn: "Prenota ora →", langLabel: "Scegli lingua",
    homeOnboardingTitle: "Inizia l'onboarding", homeOnboardingDesc: "Completa la tua configurazione legale passo dopo passo.", homeOnboardingBtn: "Inizia",
    homeDocsTitle: "I miei documenti", homeDocsDesc: "Accedi ai tuoi contratti, stato e documenti caricati.", homeDocsBtn: "Accedi",
    homeNeedHelp: "Hai bisogno di aiuto?",
  },
  ro: {
    title: "Onboarding Legal", subtitle: "Cum dorești să începi procesul de onboarding?",
    selfTitle: "Fac singur", selfDesc: "Vei fi ghidat pas cu pas prin proces — în propriul tău ritm.", selfBtn: "Începe →",
    guidedTitle: "Cu un angajat gingr", guidedDesc: "Un membru al echipei gingr te va însoți personal prin onboarding.", guidedBtn: "Programează întâlnire →",
    admin: "Panou Admin", modalTitle: "Programează întâlnire", modalSubtitle: "Onboarding cu însoțitor gingr",
    modalIntro: "Te rugăm să ai la îndemână următoarele documente înainte de programare:",
    doc1Title: "Act de identitate / Pașaport", doc1Desc: "Pașaport sau carte de identitate valabilă",
    doc2Title: "Permis de ședere", doc2Desc: "Pentru non-elvețieni: Permis B, C, L sau similar",
    doc3Title: "PFA: Dovadă de activitate", doc3Desc: "Număr UID și extras din registrul comerțului sau similar",
    bookBtn: "Programează acum →", langLabel: "Alege limba",
    homeOnboardingTitle: "Începe onboardingul", homeOnboardingDesc: "Completează-ți configurarea legală pas cu pas.", homeOnboardingBtn: "Începe",
    homeDocsTitle: "Documentele mele", homeDocsDesc: "Accesează contractele, statusul și documentele încărcate.", homeDocsBtn: "Autentificare",
    homeNeedHelp: "Ai nevoie de ajutor?",
  },
  ru: {
    title: "Правовой онбординг", subtitle: "Как вы хотите начать процесс онбординга?",
    selfTitle: "Я сделаю это сам", selfDesc: "Вы будете проходить процесс шаг за шагом — в своём собственном темпе.", selfBtn: "Начать →",
    guidedTitle: "С сотрудником gingr", guidedDesc: "Член команды gingr лично сопроводит вас через онбординг.", guidedBtn: "Записаться →",
    admin: "Панель администратора", modalTitle: "Записаться на встречу", modalSubtitle: "Онбординг с сопровождением gingr",
    modalIntro: "Пожалуйста, подготовьте следующие документы перед записью:",
    doc1Title: "Удостоверение личности / Паспорт", doc1Desc: "Действующий паспорт или удостоверение личности",
    doc2Title: "Вид на жительство", doc2Desc: "Для неграждан Швейцарии: разрешение B, C, L или аналогичное",
    doc3Title: "Самозанятые: Подтверждение деятельности", doc3Desc: "Номер UID и выписка из торгового реестра или аналогичное",
    bookBtn: "Записаться сейчас →", langLabel: "Выбрать язык",
    homeOnboardingTitle: "Начать онбординг", homeOnboardingDesc: "Пройдите юридическую настройку шаг за шагом.", homeOnboardingBtn: "Начать",
    homeDocsTitle: "Мои документы", homeDocsDesc: "Просматривайте контракты, статус и загруженные документы.", homeDocsBtn: "Войти",
    homeNeedHelp: "Нужна помощь?",
  },
  pl: {
    title: "Onboarding Prawny", subtitle: "Jak chcesz rozpocząć proces onboardingu?",
    selfTitle: "Zrobię to sam", selfDesc: "Będziesz prowadzony krok po kroku przez cały proces — we własnym tempie.", selfBtn: "Zacznij →",
    guidedTitle: "Z pracownikiem gingr", guidedDesc: "Członek zespołu gingr osobiście przeprowadzi Cię przez onboarding.", guidedBtn: "Zarezerwuj spotkanie →",
    admin: "Panel Administracyjny", modalTitle: "Zarezerwuj spotkanie", modalSubtitle: "Onboarding z asystą gingr",
    modalIntro: "Przygotuj następujące dokumenty przed rezerwacją spotkania:",
    doc1Title: "Dowód tożsamości / Paszport", doc1Desc: "Ważny paszport lub dowód osobisty",
    doc2Title: "Zezwolenie na pobyt", doc2Desc: "Dla osób spoza Szwajcarii: Zezwolenie B, C, L lub podobne",
    doc3Title: "Samozatrudnieni: Dowód działalności", doc3Desc: "Numer UID i wyciąg z rejestru handlowego lub podobne",
    bookBtn: "Zarezerwuj teraz →", langLabel: "Wybierz język",
    homeOnboardingTitle: "Rozpocznij onboarding", homeOnboardingDesc: "Ukończ konfigurację prawną krok po kroku.", homeOnboardingBtn: "Zacznij",
    homeDocsTitle: "Moje dokumenty", homeDocsDesc: "Przeglądaj swoje umowy, status i przesłane dokumenty.", homeDocsBtn: "Zaloguj się",
    homeNeedHelp: "Potrzebujesz pomocy?",
  },
  cs: {
    title: "Právní onboarding", subtitle: "Jak chcete zahájit proces onboardingu?",
    selfTitle: "Udělám to sám", selfDesc: "Budete provázeni krok za krokem procesem — vlastním tempem.", selfBtn: "Začít →",
    guidedTitle: "S pracovníkem gingr", guidedDesc: "Člen týmu gingr vás osobně provede onboardingem.", guidedBtn: "Rezervovat schůzku →",
    admin: "Administrátorský panel", modalTitle: "Rezervovat schůzku", modalSubtitle: "Onboarding s asistencí gingr",
    modalIntro: "Před rezervací schůzky si prosím připravte následující dokumenty:",
    doc1Title: "Občanský průkaz / Pas", doc1Desc: "Platný cestovní pas nebo občanský průkaz",
    doc2Title: "Povolení k pobytu", doc2Desc: "Pro neobčany Švýcarska: Povolení B, C, L nebo podobné",
    doc3Title: "OSVČ: Doklad o činnosti", doc3Desc: "Číslo UID a výpis z obchodního rejstříku nebo podobné",
    bookBtn: "Rezervovat nyní →", langLabel: "Vybrat jazyk",
    homeOnboardingTitle: "Zahájit onboarding", homeOnboardingDesc: "Dokončete svůj právní setup krok za krokem.", homeOnboardingBtn: "Začít",
    homeDocsTitle: "Moje dokumenty", homeDocsDesc: "Zobrazit smlouvy, stav a nahrané dokumenty.", homeDocsBtn: "Přihlásit se",
    homeNeedHelp: "Potřebujete pomoc?",
  },
  hu: {
    title: "Jogi Onboarding", subtitle: "Hogyan szeretné megkezdeni az onboarding folyamatot?",
    selfTitle: "Magam csinálom", selfDesc: "Lépésről lépésre vezet végig a folyamaton — a saját tempójában.", selfBtn: "Kezdés →",
    guidedTitle: "Egy gingr munkatárssal", guidedDesc: "A gingr csapat egyik tagja személyesen kíséri végig az onboardingon.", guidedBtn: "Időpont foglalása →",
    admin: "Admin irányítópult", modalTitle: "Időpont foglalása", modalSubtitle: "Onboarding gingr kísérettel",
    modalIntro: "Kérjük, készítse elő a következő dokumentumokat az időpont foglalása előtt:",
    doc1Title: "Személyi igazolvány / Útlevél", doc1Desc: "Érvényes útlevél vagy személyi igazolvány",
    doc2Title: "Tartózkodási engedély", doc2Desc: "Nem svájci állampolgároknak: B, C, L engedély vagy hasonló",
    doc3Title: "Önfoglalkoztatók: Tevékenységigazolás", doc3Desc: "UID szám és cégkivonát vagy hasonló",
    bookBtn: "Foglaljon most →", langLabel: "Nyelv kiválasztása",
    homeOnboardingTitle: "Onboarding indítása", homeOnboardingDesc: "Töltse ki a jogi beállítást lépésről lépésre.", homeOnboardingBtn: "Kezdés",
    homeDocsTitle: "Dokumentumaim", homeDocsDesc: "Tekintse meg szerződéseit, státuszát és feltöltött dokumentumait.", homeDocsBtn: "Bejelentkezés",
    homeNeedHelp: "Segítségre van szüksége?",
  },
};

export function getStoredLanguage() {
  try {
    const code = localStorage.getItem("gingr_lang") || "de";
    return LANGUAGES.find((l) => l.code === code) || LANGUAGES[0];
  } catch {
    return LANGUAGES[0];
  }
}

export function storeLanguage(lang) {
  try {
    localStorage.setItem("gingr_lang", lang.code);
  } catch {}
}